### ISSUE TITLE
Parser-Solver Mk I produces incorrect answers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#181]
```
What steps will reproduce the problem?
(9*.4)+(-6*.6)
What is the expected output?
0
What do you see instead?
4.440892098501 × 10^-16
What version of Chrome are you using?
25.0.1364.97
What operating system are you using?
Windows Xp Pro
What country are you in?
USA
Please provide any additional information below.
Just trying to figure out how it could calculate that as anything but zero....
```

Original issue reported on code.google.com by `oddityfi...@gmail.com` on 27 Feb 2013 at 4:12

**Comment by IIsi50MHz** [comment]
Caused by parser-solver Mk I.

**Comment by IIsi50MHz** [comment]
See also associated closed issues for many additional types of calculation errors caused by the parser-solver Mk I.

**Comment by IIsi50MHz** [comment]
Hmm, GitHub Android client seems to not show which other issues mention an issue? Checking for PEBKAC.

**Comment by IIsi50MHz** [comment]
Hmm, just took a while for the referenced issues to show up.

**Comment by IIsi50MHz** [comment]
Originally posted by:
> Comment by leostedile, Feb 23, 2012
> I may be mistake but I might have found a bug. These two queries output the same thing on google but not on this calculator. 0.54*0+0.34*25+0.12(25+35) (0.54*0)+(0.34*25)+(0.12(25+35)) The first one yields 11.79 and the second one 15.7

**Comment by IIsi50MHz** [comment]
Originally posted by:

> 12/3/2/2=?
> Try this: 12/3/2/2 should be equal to 1 but gives you 2.
> Posted by Kevin Kuang - 23 hours ago

(who also seems to be KevinEngineer99)

**Comment by stephenangelico** [comment]
Not sure how helpful this is now, but:
22.2-8.4-13.05-0.75 =
-1.7763568394 × 10^-15
Removing one number results in a correct calculation:
22.2-8.4-13.05 =
0.75
I don't know whether this is because it is not zero or fewer expressions.

**Comment by IIsi50MHz** [comment]
Better documented in #230
