### ISSUE TITLE
calculation error

### ISSUE THREAD

**Issue by nirmelamoud** [IIsi50MHz/chromey-calculator#248]
the following does not give the sane results
(1440129600 - 1439877659)/(60*60)

and 

(1440129600 - 1439877659)/60/60

the first give the results of 69.98361111111 which is true
the second 251941 which is false

its like the second do (1440129600 - 1439877659)/60*60

is it a bug ?

**Comment by IIsi50MHz** [comment]
This is part of issue #181 . The extension formerly relied on Google Calc and Wolfram Alpha for all calculations. With increased popularity of the extension Google began to emit a captcha response ("Are you human?"), which the extension failed to handle. As a temporary measure, a JavaScript calculator was implemented for some of the basic calculations within the browser client.

Unfortunately, the client-side Parser-Solver Mk I introduced a number of math errors. Although it is intended to be replaced with a well-established computer algebra system, finding a suitable system has been hard.

See also issue #230
