### ISSUE TITLE
Make shortcut key for opening popup user settable in options

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#51]
```
Alt+C doesn't seem to always work on all systems. Has issues in Windows (an 
error chime is often heard).

```

Original issue reported on code.google.com by `bwrobin...@gmail.com` on 19 Jul 2010 at 12:30

**Comment by IIsi50MHz** [comment]
Setting a keyboard shorcut seems unreliable in many extensions. Fortunately, Google has implemented a workaround:

 1. Open Chrome's "Settings" page.
 2. Click "Extensions".
 3. Scroll all the way to the bottom.
 4. Click "Keyboard shortcunts".
 5. Find Cloudy Calculator in the list.
 6. Click in the text box and type a keyboard shorcut, such as Alt-C.
 7. Click the "OK" button.
