### ISSUE TITLE
Division may not work when Google fails to respond

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IIsi50MHz/chromey-calculator#62]
```
What steps will reproduce the problem?
Enter any division like 12/5

What is the expected output?
I expected to get 2.4


What do you see instead?
12/5(irreducible) but I just want the result of the division not to solve a 
fraction! 

What version of Chrome are you using?
5.0.375.125

What operating system are you using?
Mac OS X

What country are you in?
US

Please provide any additional information below.

```

Original issue reported on code.google.com by `serg...@google.com` on 9 Aug 2010 at 4:53

**Comment by IIsi50MHz** [comment]
Wolfram Alpha support is deprecated at their request, so this should not happen any more. Also, the extension some time ago integrated a basic math capability of its own, so it should be sending this kind of simple query to Google any more.
